server:
  port: 8917
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://134.175.89.109:13306/jwtest?useSSL=false
    username: root
    password: ZHmi1015
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: info
